name             'cpio-downloads-server'
maintainer       'Chris Pressland'
maintainer_email 'mail@cpressland.io'
license          'All rights reserved'
description      'Installs NZBGet, Sonarr, Couch Potato and qBittorrent'
long_description 'Installs NZBGet, Sonarr, Couch Potato and qBittorrent'
version          '1.0.5'

depends          'yum'
depends          'firewalld'
depends          'selinux'
