name             'downloadbox'
maintainer       'Chris Pressland'
maintainer_email 'mail@cpressland.io'
license          'All rights reserved'
description      'Installs Nginx, NZBGet, Sonarr & CouchPotato'
long_description 'Installs Nginx, NZBGet, Sonarr & CouchPotato'
version          '2.0.0'

depends          'docker'
depends          'firewalld'
depends          'selinux'
