name             'cpio-downloads-server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cpio-downloads-server'
long_description 'Installs/Configures cpio-downloads-server'
version          '1.0.0'
depends          'yum'
depends          'firewalld'
depends          'selinux'
